accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreatView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    # 함수형 베이스 중간에 hello world
    path('hello_world/', hello_world, name="hello_world"),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # 클래스 베이스는 다름
    path('create/', AccountCreatView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),


]

practiceJangoReal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns =[
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    image = models.ImageField(upload_to='profile/', null=True)
    nickname = models.CharField(max_length=20, unique=True, null=True)
    message = models.CharField(max_length=100, null=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'nickname', 'message']

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.deocorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld

has_ownership = [account_ownership_required, login_required]


@login_required
def hello_world(request):
    if request.user.is_authenticated:

        if request.method == "POST":

            temp = request.POST.get('hello_world_input')

            new_hello_world = HelloWorld()
            new_hello_world.text = temp
            new_hello_world.save()

            hello_world_list = HelloWorld.objects.all()
            return HttpResponseRedirect(reverse('accountapp:hello_world'))
        else:
            hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})


class AccountCreatView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

profileapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from profileapp.deocorators import profile_ownership_required
from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile


class ProfileCreateView(CreateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'profileapp/create.html'

    def form_valid(self, form):
        temp_profile = form.save(commit=False)
        temp_profile.user = self.request.user
        temp_profile.save()
        return super().form_valid(form)


@method_decorator(profile_ownership_required, 'get')
@method_decorator(profile_ownership_required, 'post')
class ProfileUpdateView(UpdateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'profileapp/update.html'

accountapp/templates/accountapp/create.html
{%  extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>SignUp</h4>
        </div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{%  extends 'base.html' %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Quit</h4>
        </div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
            <img src="{{ target_user.profile.image.url }}" alt=""
                 style="height: 12rem; width:12rem; border-radius: 20rem; margin-bottom: 2rem;">

            {% if target_user.profile %}
            <h2 style="font-family: 'NanumSquareB'">
                {{ target_user.profile.nickname }}
            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                edit
            </a>
            </h2>
            {% else %}
            <a href="{% url 'profileapp:create' %}">
                <h2 style="font-family: 'NanumSquareB'">
                   Create Profile
                </h2>
            </a>
            {% endif %}
            <h5 style="margin-bottom:3rem;">
                {{ target_user.profile.message }}
            </h5>
            {% if target_user == user %}
            <a href="{% url 'accountapp:update' pk=target_user.pk %}">
                <p>
                    Change Info
                </p>
            </a>
            <a href="{% url 'accountapp:delete' pk=target_user.pk %}">
                <p>
                    Quit
                </p>
            </a>
            {% endif %}
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{%  extends 'base.html' %}

{% block content %}

        <div style="border-radius: 1rem; margin: 2rem; text-align: center">
            <h1 style="font-family: 'Tourney', cursive;">
                Hello World List!
            </h1>

            <form action="/account/hello_world/" method="post">
                {% csrf_token %}
                <div>
                    <input type="text" name="hello_world_input">
                </div>
                <div>
                    <input type="submit" class="btn btn-primary" value="POST">
                </div>
            </form>
                {% if hello_world_list %}
                     {% for hello_world in hello_world_list %}
                    <h4>
                        {{  hello_world.text }}
                    </h4>
                    {%  endfor %}
                    {%  endif %}
        </div>

    {% endblock %}

accountapp/templates/accountapp/login.html
{%  extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                <!-- {{ form }} -->
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/update.html
{%  extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Chang Info</h4>
        </div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

profileapp/templates/profileapp/create.html
{%  extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Profile Create</h4>
        </div>
        <form action="{% url 'profileapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

profileapp/templates/profileapp/update.html
{%  extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Update Info</h4>
        </div>
        <form action="{% url 'profileapp:update' pk=target_profile.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{%  include 'head.html' %}

<body style="font-family: 'NanumSquareR'">

    {%  include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {%  include 'footer.html' %}
</body>
</html>

templates/footer.html
    <div class="css_footer">
        <div class="css_footer_button">
            <span>공지사항</span> |
            <span>제휴문의</span> |
            <span>서비스 소개</span>
        </div>
        <div style="margin-top: 1rem;">
            <h6 class="css_logo">Django Practice</h6>
        </div>
    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>practiceJangoReal</title>

    <!-- 부트스트랩 LINK-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 구글폰트링크-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tourney:wght@100&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.ttf' %}") format("opentype")
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareEB.ttf' %}") format("opentype")
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareB.ttf' %}") format("opentype")
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareL.ttf' %}") format("opentype")
        }
    </style>
</head>

templates/header.html
    <div class="css_header" >
        <div>
            <h1 calss="css_logo">Django Practice</h1>
        </div>
        <div>
            <span>navl1</span>
            <span>navl2</span>
            <span>navl3</span>
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                <span>login</span>
            </a>
            <a href="{% url 'accountapp:create' %}">
                <span>SignUp</span>
            </a>
            {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                <span>MyPage</span>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                <span>logout</span>
            </a>
            {%  endif %}
        </div>
    </div>